services:
  hambot:
    image: alekmurray/hambot:latest
    container_name: hambot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /path/to/hambot/config:/app/config
    restart: unless-stopped
